export const apiEndpoints = {
  environments: () => '/environments',
  environmentDetail: (id: string | undefined) => `/environments/${id}`,
  environmentTest: (id: string) => `/environments/${id}/test`,
  environmentEnable: (id: string) => `/environments/${id}/enable`,
  streamList: (environmentId: string | null) => `/environments/${environmentId}/jetstream/streams`,
  streamDetail: (environmentId: string | null, streamName: string | undefined) => `/environments/${environmentId}/jetstream/streams/${streamName}`,
  consumerList: (environmentId: string | null, streamName: string | undefined) => `/environments/${environmentId}/jetstream/streams/${streamName}/consumers`,
  consumerDetail: (environmentId: string | null, streamName: string | undefined, consumerName: string | undefined) => `/environments/${environmentId}/jetstream/streams/${streamName}/consumers/${consumerName}`,
  streamMessages: (environmentId: string | null, streamName: string | undefined) => `/environments/${environmentId}/jetstream/streams/${streamName}/messages`,
  kvBuckets: (environmentId: string | null) => `/environments/${environmentId}/kv/buckets`,
  kvBucket: (environmentId: string | null, bucketName: string | undefined) => `/environments/${environmentId}/kv/buckets/${bucketName}`,
  kvKeys: (environmentId: string | null, bucketName: string | undefined) => `/environments/${environmentId}/kv/buckets/${bucketName}/keys`,
  kvKey: (environmentId: string | null, bucketName: string | undefined, key: string | undefined) => `/environments/${environmentId}/kv/buckets/${bucketName}/keys/${key}`,
  kvKeyHistory: (environmentId: string | null, bucketName: string | undefined, key: string | undefined) => `/environments/${environmentId}/kv/buckets/${bucketName}/keys/${key}/history`,
  objectBuckets: (environmentId: string | null) => `/environments/${environmentId}/objectstore/buckets`,
  objectBucket: (environmentId: string | null, bucketName: string | undefined) => `/environments/${environmentId}/objectstore/buckets/${bucketName}`,
  objects: (environmentId: string | null, bucketName: string | undefined) => `/environments/${environmentId}/objectstore/buckets/${bucketName}/objects`,
  objectInfo: (environmentId: string | null, bucketName: string | undefined, objectName: string | undefined) => `/environments/${environmentId}/objectstore/buckets/${bucketName}/objects/${objectName}`,
  objectUpload: (environmentId: string | null, bucketName: string | undefined, objectName: string) => `/environments/${environmentId}/objectstore/buckets/${bucketName}/objects/${objectName}/upload`,
  coreNatsStatus: (environmentId: string | null) => `/environments/${environmentId}/core-nats/status`,
  coreNatsSubjects: (environmentId: string | null) => `/environments/${environmentId}/core-nats/subjects`,
  coreNatsPublish: (environmentId: string | null) => `/environments/${environmentId}/core-nats/publish`,
  coreNatsStream: (environmentId: string | null, subject: string) => `/environments/${environmentId}/core-nats/stream?subject=${encodeURIComponent(subject)}`,
  auditEvents: () => '/audit/events',
  users: () => '/access-control/users',
  roles: () => '/access-control/roles',
  userRoles: (userId: string | undefined) => `/access-control/users/${userId}/roles`,
  userRole: (userId: string, assignmentId: string) => `/access-control/users/${userId}/roles/${assignmentId}`,
  dashboard: (environmentId: string | null) => `/environments/${environmentId}/monitoring/dashboard`,
  clusterOverview: (environmentId: string | null) => `/environments/${environmentId}/monitoring/cluster/overview`,
} as const;

export const toApiUrl = (path: string) => `/api${path}`;
