import type { PaginatedQueryParams } from './types';

export const queryKeys = {
  environments: () => ['environments'] as const,
  environmentList: (params?: PaginatedQueryParams) => ['environments', 'list', params ?? null] as const,
  environmentDetail: (id?: string) => ['environments', 'detail', id ?? null] as const,
  dashboardRoot: () => ['dashboard'] as const,
  dashboard: (environmentId: string | null) => ['dashboard', environmentId] as const,
  streamsRoot: (environmentId: string | null) => ['jetstream', 'streams', environmentId] as const,
  streams: (environmentId: string | null, params?: PaginatedQueryParams) => ['jetstream', 'streams', environmentId, params ?? null] as const,
  streamDetail: (environmentId: string | null, streamName?: string) => ['jetstream', 'stream', environmentId, streamName ?? null] as const,
  consumersRoot: (environmentId: string | null, streamName?: string) => ['jetstream', 'consumers', environmentId, streamName ?? null] as const,
  consumers: (environmentId: string | null, streamName?: string, params?: PaginatedQueryParams) => ['jetstream', 'consumers', environmentId, streamName ?? null, params ?? null] as const,
  consumerDetail: (environmentId: string | null, streamName?: string, consumerName?: string) => ['jetstream', 'consumer', environmentId, streamName ?? null, consumerName ?? null] as const,
  streamMessages: (environmentId: string | null, streamName?: string, startSequence?: number, count?: number) => ['jetstream', 'messages', environmentId, streamName ?? null, startSequence ?? null, count ?? null] as const,
  kvBuckets: (environmentId: string | null) => ['kv', 'buckets', environmentId] as const,
  kvBucket: (environmentId: string | null, bucketName?: string) => ['kv', 'bucket', environmentId, bucketName ?? null] as const,
  kvKeys: (environmentId: string | null, bucketName?: string, search?: string) => ['kv', 'keys', environmentId, bucketName ?? null, search ?? null] as const,
  kvKey: (environmentId: string | null, bucketName?: string, key?: string) => ['kv', 'key', environmentId, bucketName ?? null, key ?? null] as const,
  kvKeyHistory: (environmentId: string | null, bucketName?: string, key?: string) => ['kv', 'key-history', environmentId, bucketName ?? null, key ?? null] as const,
  objectBuckets: (environmentId: string | null) => ['objectstore', 'buckets', environmentId] as const,
  objectBucket: (environmentId: string | null, bucketName?: string) => ['objectstore', 'bucket', environmentId, bucketName ?? null] as const,
  objects: (environmentId: string | null, bucketName?: string) => ['objectstore', 'objects', environmentId, bucketName ?? null] as const,
  objectInfo: (environmentId: string | null, bucketName?: string, objectName?: string) => ['objectstore', 'object', environmentId, bucketName ?? null, objectName ?? null] as const,
  coreNatsStatus: (environmentId: string | null) => ['core-nats', 'status', environmentId] as const,
  coreNatsSubjects: (environmentId: string | null) => ['core-nats', 'subjects', environmentId] as const,
  auditEvents: (params: Record<string, unknown>) => ['audit', 'events', params] as const,
  users: () => ['admin', 'users'] as const,
  roles: () => ['admin', 'roles'] as const,
  userRoles: (userId?: string) => ['admin', 'user-roles', userId ?? null] as const,
  clusterOverview: (environmentId: string | null) => ['monitoring', 'cluster-overview', environmentId] as const,
} as const;
